name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger the workflow on push events to the main branch.
  pull_request:
    branches:
      - main # Also trigger on pull requests to the main branch.

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run the job on an Ubuntu runner.

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Sets up Docker Buildx

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set in your repo's secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set in your repo's secrets

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Directory of Dockerfile
          file: ./Dockerfile
          push: true # Push image to Docker Hub
          tags: happyjake/localsend-rs:latest
